# DATA_PATH: ./data/raw/rajapakse_fixed_material/rajapakse_fixed_v1.npz
data_filename: /Volumes/tmh/new_data/rajapakse_fixed_material/rajapakse_fixed_v2.npz

seed: 42

# ---------------------- Influence function dynamic single material problem -----------------

N_r: 40 # Mesh points for r coordinate
N_z: 40 # Mesh points for z coordinate
r_min: 0 # Min r coordinate sampled [m]
z_min: 0 # Min. z coordinate sampled   [m]
r_max: 10 # Max. r coordinate sampled [m]
z_max: 10 # Max. z coordinate sampled [m]

N: 500 # Number of samples

omega_min: 0 # Min. sampled frequency [Rad/s]
omega_max: 5200 # Max. sampled frequency [Rad/s]
load: 6006663.0 # Load magnitude [N]
z_source: 0 # Position of source load in z axis [m]
l_source: 0 # Dimension of source load in z axis [m]
r_source: 2 # Dimension of source load in r axis [m]

E: 25.0E+09 # Young Modulus [Pa]
nu: 2.42277267E-01 # Poisson's ratio
damp: 0.01 # Damping factor
dens: 1.73511990E+03 # Density [Kg.m-3]

component:
  1 # uzz :  1
  # urz :  2
  # szzz : 3
  # srzz : 4
  # srrz : 5
  # uzr :  6
  # urr :  7
  # szzr : 8
  # srzr : 9
  # srrr : 10

loadtype:
  3 # pointload    1
  # ringload     2
  # diskload     3
  # cylinderload 4
  # anularload   5

bvptype:
  2 # loadinfullspace :   1
  # loadoverhalfspace : 2
  # loadinhalfspace :   3
  # cylinderload :      4
  # anularload :        5
