# Parameters for training DeepONets.
MODEL_NAME: 20250308_DeepONet_dynamic_100_basis_pod_in_norm_2_trunk_exp_fts_split

# Location of test file info
DATA_FILE: ./data/raw/dynamic_displacements.npz

# Model location
MODEL_FOLDER_TO_LOAD: "./models/dynamic/pod/split_outputs/20250308_DeepONet_dynamic_100_basis_pod_in_norm_2_trunk_exp_fts_split"

# Location of outputs (data, plots)
OUTPUT_FOLDER: ./data/output/
IMAGES_FOLDER: ./models/dynamic/pod/split_outputs/20250308_DeepONet_dynamic_100_basis_pod_in_norm_2_trunk_exp_fts_split/images/

# Data type, device, and error norm
PRECISION: float32
DEVICE: cpu

PLOT_FIELD: true
PLOT_AXIS: true
PLOT_BASIS: true

AXES_TO_PLOT:
  - x
  - z

# Plot every X percentile (e.g every 10th percentile of the input functions)
PLOT_PERCENTILES: 10

INFERENCE_ON: test
SAMPLES_TO_PLOT: 5
BASIS_TO_PLOT: all
PRINCIPAL_MODES_TO_PLOT: 4
PLOT_FIELD_BAR_COLOR: cyan
PLOT_BASIS_BAR_COLOR: magenta