# ------------------- Model architecture ------------------
seed: 42
training_strategy: vanilla
output_handling: single_output
num_basis_functions: 30
branch:
  architecture: resnet
  activation: silu
  degree: 8
  hidden_layers:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
trunk:
  architecture: resnet
  activation: silu
  degree: 8
  hidden_layers:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
loss_function: mse
transforms:
  branch:
    normalization: null
    feature_expansion: null
  trunk:
    normalization: min_max_0_1  # min_max_0_1, min_max_-1_1, standardize, null
    feature_expansion:
      type: cosine
      size: 10
  output_normalization: null
rescaling: 
  type: null
  exponent: -1 #  Used to rescale the output of the DeepONet by the number of basis functions to the power of the exponent (use exponent < 0).

# ------------------- Parameters for vanilla training ------------------
learning_rate: 0.001
epochs: 10
branch_batch_size: 50
trunk_batch_size: null
error: vector_l2
standard_progress_bar_color: 'green'
global_optimizer_schedule:
  - epochs: 5000
    optimizer: adam
    learning_rate: 0.0001
    l2_regularization: 0.0001
    lr_scheduler:
      step_size: 1000
      gamma: 0.7

# ------------------- Parameters for POD training ----------------------
num_pod_modes: 10

# ------------------- Parameters for two step training ------------------
trunk_epochs: 150
branch_epochs: 500  
decomposition_type: svd

two_step_optimizer_schedule:
  trunk:
    - epochs: 10000
      optimizer: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
    - epochs: 30000
      optimizer: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        step_size: 5000
        gamma: 0.7
    - epochs: 110000
      optimizer: adam
      learning_rate: 0.0005
      l2_regularization: 0.00001
  branch:
    - epochs: 50000
      optimizer: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        step_size: 5000
        gamma: 0.7
    - epochs: 50000
      optimizer: adam
      learning_rate: 0.0001
      l2_regularization: 0.00001
      lr_scheduler:
        step_size: 10000
        gamma: 0.5
    - epochs: 50000
      optimizer: adam
      learning_rate: 0.0001
      l2_regularization: 0.00001
      lr_scheduler:
        step_size: 10000
        gamma: 0.5
