# ------------------- Model architecture ------------------
seed: 42
training_strategy: vanilla
output_handling: single_output
num_basis_functions: 100
branch:
  architecture: resnet
  activation: silu
  degree: 8
  hidden_layers:
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
trunk:
  architecture: resnet
  activation: silu
  degree: 8
  hidden_layers:
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
    - 500 
loss_function: mse
transforms:
  branch:
    normalization: min_max_0_1
    feature_expansion: null
  trunk:
    normalization: min_max_0_1  # min_max_0_1, min_max_-1_1, standardize, null
    feature_expansion:
      type: cosine
      size: 1
  target:
    normalization: null
rescaling: 
  type: null
  exponent: 0 #  Used to rescale the output of the DeepONet by the number of basis functions to the power of the exponent (use exponent < 0).

# ------------------- Parameters for vanilla training ------------------
epochs: 2000
branch_batch_size: 64
trunk_batch_size: 64
error: vector_l2
optimizer_schedule:
  - epochs: 1000
    optimizer_type: adam
    learning_rate: 0.0001
    l2_regularization: 0.0001
    lr_scheduler:
      type: step
      step_size: 2000
      gamma: 0.7
  - epochs: 1000
    optimizer_type: sgd
    learning_rate: 0.001
    l2_regularization: 0.00001
    lr_scheduler:
      type: step
      step_size: 1000
      gamma: 0.4

# ------------------- Parameters for POD training ----------------------
num_pod_modes: 10

# ------------------- Parameters for two step training ------------------
trunk_epochs: 150
branch_epochs: 500  
decomposition_type: svd

two_step_optimizer_schedule:
  trunk_phase:
    - epochs: 10000
      optimizer_type: sgd
      learning_rate: 0.01
      l2_regularization: 0.00001
    - epochs: 30000
      optimizer_type: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 5000
        gamma: 0.7
    - epochs: 110000
      optimizer_type: adam
      learning_rate: 0.0005
      l2_regularization: 0.00001
  branch_phase:
    - epochs: 50000
      optimizer_type: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 5000
        gamma: 0.7
    - epochs: 50000
      optimizer_type: adam
      learning_rate: 0.0001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 10000
        gamma: 0.5
    - epochs: 50000
      optimizer_type: adam
      learning_rate: 0.0001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 10000
        gamma: 0.5
