# ------------------- Model architecture ------------------
seed: 42
training_strategy: pod
output_handling: shared_trunk
num_basis_functions: 30
branch:
  architecture: resnet
  activation: relu
  hidden_layers: [256, 256, 128, 128, 128]
  dropout_rates: [0.0, 0.0, 0.0, 0.1, 0.0, 0.0]
  batch_normalization: [False, False, False, False, False, False]
  layer_normalization: [False, False, False, False, False, False]
  degree: 8
trunk:
  architecture: resnet
  activation: relu
  hidden_layers: [256, 256, 128, 128, 128]
  dropout_rates: [0.0, 0.0, 0.0, 0.1, 0.1, 0.0]
  batch_normalization: [False, True, False, False, False, False]
  layer_normalization: [False, False, False, True, False, False]
  degree: 8
loss_function: mse
transforms:
  branch:
    normalization: standardize
    feature_expansion: null
  trunk:
    normalization: minmax_-1-1 # minmax_0_1, minmax_-1_1, standardize, null
    feature_expansion:
      # null
      type: cosine
      size: 5
  target:
    normalization: null
rescaling:
  exponent: 0 #  Used to rescale the output of the DeepONet by the number of basis functions to the power of the exponent (use exponent < 0).

# --------------------- POD Config ----------------------
pod: by_channel # stacked or by_channel

# ------------------- Parameters for vanilla / pod training ------------------
branch_batch_size: 400 # Can't be null
trunk_batch_size: null
error: matrix_fro
optimizer_schedule:
  - epochs: 400
    optimizer_type: adam
    learning_rate: 0.001
    l2_regularization: 0.0000
    lr_scheduler:
      type: step
      step_size: 2000
      gamma: 0.5

# ------------------- Parameters for two step training ------------------
decomposition_type: svd

two_step_optimizer_schedule:
  trunk_phase:
    - epochs: 500
      optimizer_type: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 500
        gamma: 0.7

  branch_phase:
    - epochs: 1000
      optimizer_type: adam
      learning_rate: 0.001
      l2_regularization: 0.00001
      lr_scheduler:
        type: step
        step_size: 500
        gamma: 0.7
