# Parameters for training DeepONets.
MODELNAME: 20250224_DeepONet_dynamic_standard_in_norm_trunkexp_splitbasis

# Location of test file info
DATAFILE: ./data/raw/kelvin_displacements.npz

# Model & outputs location
MODEL_FOLDER: ./models/

# Data type, device, and error norm
PRECISION: float32
DEVICE: cpu

PLOT_FIELD: true
PLOT_AXIS: true
PLOT_BASIS: true

AXES_TO_PLOT:
- r
- z

# Plot every X percentile (e.g every 10th percentile of the input functions)
PLOT_PERCENTILES: 10

INFERENCE_ON: test
SAMPLES_TO_PLOT: 5
BASIS_TO_PLOT: 20

# For two-step:
PHASE: final