#  ----------------------Location of .npz data file ----------------
DATAFILE: ./data/raw/dynamic_displacements.npz

# ------------------------------ Paths ------------------------
# Model location
MODEL_FOLDER: ./models/

# ------------------------- Dataset parameters ---------------
PROBLEM: dynamic

INPUT_FUNCTION_KEYS: # F, mu, nu if Kelvin ; delta if dynamic (xb for now)
-  xb

COORDINATE_KEYS:
- r
- z

OUTPUT_KEYS:
- g_u_real
- g_u_imag

DIRECTION: 2

# ------------------- Model architecture ------------------
PRECISION: float32
DEVICE: cpu
SEED: 42

LOSS_FUNCTION: mse
TRAINING_STRATEGY: standard
OUTPUT_HANDLING: split_networks
BASIS_FUNCTIONS: 5
BRANCH_ARCHITECTURE: resnet
BRANCH_ACTIVATION: relu
BRANCH_DEGREE: 8
BRANCH_HIDDEN_LAYERS:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 

TRUNK_ARCHITECTURE: resnet
TRUNK_ACTIVATION: relu
TRUNK_DEGREE: 8
TRUNK_HIDDEN_LAYERS:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 

INPUT_NORMALIZATION: true
OUTPUT_NORMALIZATION: false
TRUNK_FEATURE_EXPANSION: true
TRUNK_EXPANSION_FEATURES_NUMBER: 10

# ------------------- Parameters for vanilla training ------------------
LEARNING_RATE: 0.0001
EPOCHS: 5000
BATCH_SIZE: 50
TRAIN_PERC: 0.8
VAL_PERC: 0.1
TEST_PERC: 0.1
ERROR_NORM: 2
L2_REGULARIZATION: 0.00001 #implement L1, L2 and penalty
EARLY_STOPPING: false
LR_SCHEDULING: true
SCHEDULER_STEP_SIZE: 3000
SCHEDULER_GAMMA: 0.5
CHANGE_OPTIMIZER: false # Not implemented
DEFAULT_CHANGE_AT_EPOCH: 5000
STANDARD_PROGRESS_BAR_COLOR: 'green'

# ------------------- Parameters for POD training ----------------------
VAR_SHARE: 0.999
POD_PROGRESS_BAR_COLOR: 'yellow'

# ------------------- Parameters for two step training ------------------
TRUNK_TRAIN_EPOCHS: 5000
TRUNK_DECOMPOSITION: svd
TRUNK_LEARNING_RATE: 0.001
TRUNK_L2_REGULARIZATION: 0.0000001
TRUNK_EARLY_STOPPING: false
TRUNK_LR_SCHEDULING: true
TRUNK_SCHEDULER_STEP_SIZE: 2000
TRUNK_SCHEDULER_GAMMA: 0.5
TRUNK_CHANGE_OPTIMIZER: true
TRUNK_CHANGE_AT_EPOCH: 8000
TRUNK_PROGRESS_BAR_COLOR: 'black'

BRANCH_TRAIN_EPOCHS: 5000
BRANCH_LEARNING_RATE: 0.001
BRANCH_L2_REGULARIZATION: 0.0000001
BRANCH_EARLY_STOPPING: false
BRANCH_LR_SCHEDULING: true
BRANCH_SCHEDULER_STEP_SIZE: 2000
BRANCH_SCHEDULER_GAMMA: 0.25
BRANCH_CHANGE_OPTIMIZER: true
BRANCH_CHANGE_AT_EPOCH: 8000
BRANCH_PROGRESS_BAR_COLOR: 'white'