#  ----------------------Location of .npz data file ----------------
DATAFILE: ./data/raw/displacements.npz

# ------------------------------ Paths ------------------------
# Model location
MODEL_FOLDER: ./models/

# ------------------------- Dataset parameters ---------------
PROBLEM: dynamic

INPUT_FUNCTION_KEYS: # F, mu, nu if Kelvin ; delta if dynamic (xb for now)
-  delta

COORDINATE_KEYS:
- r
- z

OUTPUT_KEYS:
- g_u_real
- g_u_imag

DIRECTION: 2

# ------------------- Model architecture ------------------
PRECISION: float32
DEVICE: cpu
SEED: 42

LOSS_FUNCTION: mse
TRAINING_STRATEGY: standard
EPOCHS_PER_PHASE: [10000]
OUTPUT_HANDLING: split_outputs
BASIS_FUNCTIONS: 40
BRANCH_ARCHITECTURE: resnet
BRANCH_ACTIVATION: relu
BRANCH_DEGREE: 8
BRANCH_HIDDEN_LAYERS:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 

TRUNK_ARCHITECTURE: resnet
TRUNK_ACTIVATION: relu
TRUNK_DEGREE: 8
TRUNK_HIDDEN_LAYERS:
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 
    - 100 

INPUT_NORMALIZATION: true # allow to pick between min max and std 
OUTPUT_NORMALIZATION: false
TRUNK_FEATURE_EXPANSION: 10

# ------------------- Parameters for vanilla training ------------------
LEARNING_RATE: 0.001
EPOCHS: 5000
BATCH_SIZE: 50
TRAIN_PERC: 0.8
VAL_PERC: 0.1
TEST_PERC: 0.1
ERROR_NORM: 2
STANDARD_PROGRESS_BAR_COLOR: 'green'
OPTIMIZER_SCHEDULE: 
    - EPOCHS: 10000
      OPTIMIZER: adam
      LEARNING_RATE: 0.001
      L2_REGULARIZATION: 0.00001
      LR_SCHEDULER:
        STEP_SIZE: 2000
        GAMMA: 0.7
    - EPOCHS: 10000
      OPTIMIZER: adam
      LEARNING_RATE: 0.0001
      L2_REGULARIZATION: 0.00001


# ------------------- Parameters for POD training ----------------------
VAR_SHARE: 0.999

# ------------------- Parameters for two step training ------------------
TRUNK_TRAIN_EPOCHS: 3000
TRUNK_DECOMPOSITION: svd

BRANCH_TRAIN_EPOCHS: 4000
BRANCH_OPTIMIZER: adam