PRECISION: float32
DEVICE: cpu

# Location of dataset to test
PROCESSED_DATA_PATH: ./data/processed/kelvin/processed_kelvin_data.npz

# Location of outputs (data, metrics) - Set this if testing a pretrained model
OUTPUT_PATH: ./output/kelvin/

PLOT_FIELD: true
PLOT_AXIS: true
PLOT_BASIS: true

AXES_TO_PLOT:
  - x
  - y
  - z

# Plot every X percentile (e.g every 10th percentile of the input functions)
PLOT_PERCENTILES: 10

INFERENCE_ON: test
SAMPLES_TO_PLOT: 5
BASIS_TO_PLOT: all
PRINCIPAL_MODES_TO_PLOT: 4
PLOT_FIELD_BAR_COLOR: cyan
PLOT_BASIS_BAR_COLOR: magenta