#  ----------------------Location of .npz data files ----------------
raw_data_path: ./data/raw/kelvin/kelvin_v4.npz
dataset_version: 

# ------------------------- Dataset parameters ----------------
problem: kelvin
splitting:
  ratios: [0.8, 0.1, 0.1]
  seed: 42

data_labels:
  features: [xb, xt]
  targets: [g_u]

input_function_keys:  
  - nu
  - mu

input_function_labels:
  - ν
  - μ 

coordinate_keys:
  - x
  - y
  - z

output_keys:
  - g_u_x
  - g_u_y
  - g_u_z

output_labels:
  - "$\\u_x$"
  - "$\\u_y$"
  - "$\\u_z$"

load_direction: z

var_share: 0.95