precision: float32
device: cpu

# Location of dataset to test
experiment_version: 2025-07-22_01-36-34

# Location of outputs (data, metrics) - Set this if testing a pretrained model
output_path: ./output
processed_data_path: ./data/processed

plot_plane: false
plot_axis: false
plot_basis: false
plot_coefficients: true
plot_coefficients_mean: false

# Plot every X percentile (e.g every 10th percentile of the input functions)
percentiles: 10
vectors_to_highlight: 3
