precision: float32
device: cpu

# Location of dataset to test
experiment_version: 2025-06-25_20-43-10

# Location of outputs (data, metrics) - Set this if testing a pretrained model
output_path: ./output
processed_data_path: ./data/processed

plot_field: true
plot_axis: true
plot_basis: true

axes_to_plot:
  - x
  - y
  - z

# Plot every X percentile (e.g every 10th percentile of the input functions)
plot_percentiles: 10
inference_on: test
samples_to_plot: 5
basis_to_plot: all
principal_modes_to_plot: 4
plot_field_bar_color: cyan
plot_basis_bar_color: magenta