DATA_PATH: ./data/raw/kelvin/kelvin_v1.npz

SEED: 42

# -------------------------- Kelvin Problem -----------------------

N: 10000
F_MIN: 6        # log10 [N] (1 MN)
F_MAX: 7        # log10 [N] (10 MN)
MU_MIN: 5       # log10 [Pa] (0.1 MPa)
MU_MAX: 8   # log10 [Pa] (100 MPa)
NU_MIN: 0.1
NU_MAX: 0.45

N_X: 10
N_Y: 10
N_Z: 40
X_MIN: 0.01
X_MAX: 1
Y_MIN: 0.01
Y_MAX: 1
Z_MIN: 0.1
Z_MAX: 1
LOAD_DIRECTION: z