data_filename: ./data/raw/kelvin/kelvin_v4.npz

seed: 42

# -------------------------- Kelvin Problem -----------------------

N: 500
F: 5        # log10 [N] (10 MN)
mu_min: 6       # log10 [Pa] (1 MPa)
mu_max: 8   # log10 [Pa] (100 MPa)
nu_min: 0.01
nu_max: 0.5

N_x: 30
N_y: 30
N_z: 20
x_min: -0.1
x_max: 0.1
y_min: -0.1
y_max: 0.1
z_min: -0.1
z_max: 0.1
load_direction: z

scaler: 1 # Scale parameter for mesh transformation