DATA_FILENAME: ./data/raw/displacements.npz

SEED: 42

# ---------------------- Influence function dynamic problem -----------------

N_R: 40                   # Mesh points for r coordinate
N_Z: 40                   # Mesh points for z coordinate
R_MIN: 0               # Min r coordinate sampled [m]
Z_MIN: 0                  # Min. z coordinate sampled   [m]
R_MAX: 20                 # Max. r coordinate sampled [m]
Z_MAX: 20                 # Max. z coordinate sampled [m]

N : 500              # Number of samples

OMEGA_MIN: 0            # Min. sampled frequency [Rad/s]
OMEGA_MAX: 5200           # Max. sampled frequency [Rad/s]
LOAD: 6006663.0           # Load magnitude [N]
Z_SOURCE: 0             # Position of source load in z axis [m]
L_SOURCE: 0             # Dimension of source load in z axis [m]
R_SOURCE: 2             # Dimension of source load in r axis [m]

E: 25E+09              # Young Modulus [Pa]
NU: 2.42277267E-01         # Poisson's ratio
DAMP: 0.01             # Damping factor
DENS: 1.73511990E+03    # Density [Kg.m-3]


COMPONENT: 1            # uzz :  1
                        # urz :  2
                        # szzz : 3
                        # srzz : 4
                        # srrz : 5
                        # uzr :  6
                        # urr :  7
                        # szzr : 8
                        # srzr : 9
                        # srrr : 10

LOADTYPE: 3             # pointload    1
                        # ringload     2
                        # diskload     3
                        # cylinderload 4
                        # anularload   5

BVPTYPE: 2              # loadinfullspace :   1
                        # loadoverhalfspace : 2
                        # loadinhalfspace :   3
                        # cylinderload :      4
                        # anularload :        5

# -------------------------- Static Problem (Kelvin) -----------------------

N_MU_KELVIN: 10
MU_MIN_KELVIN: 0.5
MU_MAX_KELVIN: 3

N_NU_KELVIN: 10
NU_MIN_KELVIN: 0.1
NU_MAX_KELVIN: 0.45

N_F_KELVIN: 5
F_MIN_KELVIN: 1
F_MAX_KELVIN: 100

N_X_KELVIN: 50
N_Y_KELVIN: 1
N_Z_KELVIN: 50
X_MIN_KELVIN: 0.01
X_MAX_KELVIN: 2
Y_MIN_KELVIN: 0.01
Y_MAX_KELVIN: 1
Z_MIN_KELVIN: 0.1
Z_MAX_KELVIN: 3
LOAD_DIRECTION_KELVIN: z