DATA_FILENAME: ./data/raw/dynamic_homogeneous_displacements.npz

SEED: 42

# ---------------------- Influence function dynamic single material problem -----------------

N_R: 40                   # Mesh points for r coordinate
N_Z: 40                   # Mesh points for z coordinate
R_MIN: 0               # Min r coordinate sampled [m]
Z_MIN: 0                  # Min. z coordinate sampled   [m]
R_MAX: 20                 # Max. r coordinate sampled [m]
Z_MAX: 20                 # Max. z coordinate sampled [m]

N : 500              # Number of samples

OMEGA_MIN: 0            # Min. sampled frequency [Rad/s]
OMEGA_MAX: 5200           # Max. sampled frequency [Rad/s]
LOAD: 6006663.0           # Load magnitude [N]
Z_SOURCE: 0             # Position of source load in z axis [m]
L_SOURCE: 0             # Dimension of source load in z axis [m]
R_SOURCE: 2             # Dimension of source load in r axis [m]

E_MIN: 1.0E+07              # Min. Young Modulus [Pa]
E_MAX: 2.0E+11              # Max. Young Modulus [Pa]
NU_MIN: 0.2         # Min. Poisson's ratio
NU_MAX: 0.4         # Max. Poisson's ratio
DENS_MIN: 1.0E+03    # Min. Density [Kg.m-3]
DENS_MAX: 8.0E+03    # Max. Density [Kg.m-3]
DAMP: 0.01             # Damping factor

COMPONENT: 1            # uzz :  1
                        # urz :  2
                        # szzz : 3
                        # srzz : 4
                        # srrz : 5
                        # uzr :  6
                        # urr :  7
                        # szzr : 8
                        # srzr : 9
                        # srrr : 10

LOADTYPE: 3             # pointload    1
                        # ringload     2
                        # diskload     3
                        # cylinderload 4
                        # anularload   5

BVPTYPE: 2              # loadinfullspace :   1
                        # loadoverhalfspace : 2
                        # loadinhalfspace :   3
                        # cylinderload :      4
                        # anularload :        5